services:

# HOMARR
  homarr:
    image: ghcr.io/homarr-labs/homarr:${VERSION_HOMARR}
    container_name: homarr
    restart: unless-stopped
    environment:
      DOCKER_HOSTNAMES: dockerproxy
      DOCKER_PORTS: 2375
      SECRET_ENCRYPTION_KEY: ${ENV_SECRET_ENCRYPTION_KEY}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/docker/homarr/appdata:/appdata
    networks:
      - net
    ports:
      - ${PORT1_HOMARR}:7575

# UPTIME-KUMA
  uptime-kuma:
    image: louislam/uptime-kuma:${VERSION_UPTIME_KUMA}
    container_name: uptime-kuma
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/docker/uptime-kuma/data:/app/data
    networks:
      - net
    ports:
      - ${PORT1_UPTIME_KUMA}:3001

# BESZEL
  beszel:
    image: henrygd/beszel:${VERSION_BESZEL}
    container_name: beszel
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/docker/beszel/data:/beszel_data
      - /home/docker/beszel/socket:/beszel_socket
    networks:
      - net
    ports:
      - ${PORT1_BESZEL}:8090

  beszel-agent:
    image: henrygd/beszel-agent:${VERSION_BESZEL}
    container_name: beszel-agent
    restart: unless-stopped
    network_mode: host
    environment:
      LISTEN: /beszel_socket/beszel.sock
      HUB_URL: http://localhost:${PORT1_BESZEL}
      TOKEN: ${ENV_BESZEL_TOKEN}
      KEY: ${ENV_BESZEL_KEY}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /home/docker/beszel/agent/data:/var/lib/beszel-agent
      - /home/docker/beszel/socket:/beszel_socket
      - ${VOL1}/.beszel:/extra-filesystems/md0:ro
    
# AUTOHEAL
  autoheal:
    deploy:
      replicas: 1
    image: willfarrell/autoheal:${VERSION_AUTOHEAL}
    container_name: autoheal
    restart: unless-stopped
    environment:
      AUTOHEAL_CONTAINER_LABEL: all
      AUTOHEAL_INTERVAL: 30
      AUTOHEAL_START_PERIOD: 0
      AUTOHEAL_DEFAULT_STOP_TIMEOUT: 20
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
    network_mode: none

# DOCKERPROXY
  dockerproxy:
    image: linuxserver/socket-proxy:${VERSION_DOCKERPROXY}
    container_name: dockerproxy
    restart: unless-stopped
    environment:
      CONTAINERS: 1
      SERVICES: 0
      TASKS: 0
      POST: 1
    ports:
      - ${PORT1_DOCKERPROXY}:2375
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - net

      
networks:
  net:
    driver: bridge
