services:

# GLUETUN
  gluetun:
    image: qmcgaw/gluetun:${VERSION_GLUETUN}
    container_name: gluetun
    restart: always
    hostname: gluetunnet
    # line above must be uncommented to allow external containers to connect.
    cap_add:
      - NET_ADMIN
    environment:
      TZ: ${ENV_TZ}
      FIREWALL_OUTBOUND_SUBNETS: ${ENV_FIREWALL_OUTBOUND_SUBNETS}
      VPN_SERVICE_PROVIDER: ${ENV_VPN_SERVICE_PROVIDER}
      VPN_TYPE: ${ENV_VPN_TYPE}
      OWNED_ONLY: yes
      WIREGUARD_PRIVATE_KEY: ${ENV_WIREGUARD_PRIVATE_KEY}
      WIREGUARD_ADDRESSES: ${ENV_WIREGUARD_ADDRESSES}
      SERVER_HOSTNAMES: ${ENV_SERVER_HOSTNAMES}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/docker/gluetun:/gluetun
    devices:
      - /dev/net/tun:/dev/net/tun
    networks:
      - net
    ports:
      - ${PORT1_GLUETUN}:8000 
      - ${PORT1_QBITTORRENT}:8080
      - ${PORT2_QBITTORRENT}:6881
      - ${PORT2_QBITTORRENT}:6881/udp
      - ${PORT1_SABNZBD}:8081
      - ${PORT1_SLSKD}:5030
      - ${PORT2_SLSKD}:5031
      - ${PORT3_SLSKD}:50300
      - ${PORT1_JACKETT}:9117
      - ${PORT1_LIDARR}:8686
      - ${PORT1_RADARR}:7878
      - ${PORT1_SONARR}:8989
      - ${PORT1_SOULMATE}:7373

# QBITTORRENT
  qbittorrent:
    image: linuxserver/qbittorrent:${VERSION_QBITTORRENT}
    container_name: qbittorrent
    restart: unless-stopped
    network_mode: service:gluetun
    healthcheck:
      test: "curl ifconfig.me  || exit 1"
      interval: 1m
      timeout: 10s
    deploy:
      resources:
        limits:
          memory: 8192M
    environment:
      PUID: 1000
      PGID: 1000
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/docker/qbittorrent/config:/config
      - /home/docker/qbittorrent/torrentfiles:/torrentfiles
      - /home/docker/qbittorrent/webui:/webui
      - ${VOL1}/Library/Torrents:/downloads

# SABNZBD
  sabnzbd:
    image: linuxserver/sabnzbd:${VERSION_SABNZBD}
    container_name: sabnzbd
    restart: unless-stopped
    network_mode: service:gluetun
    healthcheck:
      test: "curl ifconfig.me  || exit 1"
      interval: 1m
      timeout: 10s
    environment:
      PUID: 1000
      PGID: 1000
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/docker/sabnzbd/config:/config
      - ${VOL1}/Library/Usenet:/downloads
      - ${VOL1}/Library/Usenet/incomplete:/incomplete-downloads
      - ${VOL1}/Backups/Container/SABnzbd:/backups

# SLSKD
  slskd:
    image: slskd/slskd:${VERSION_SLSKD}
    container_name: slskd
    restart: unless-stopped
    network_mode: service:gluetun
    healthcheck:
      test: "wget -q -O- ifconfig.me  || exit 1"
      interval: 1m
      timeout: 10s
    environment:
      PUID: 1000
      PGID: 1000
      SLSKD_REMOTE_CONFIGURATION: true
      SLSKD_UMASK: 002
      SLSKD_FILE_PERMISSION_MODE: 666
      SLSKD_DOWNLOADS_DIR: /downloads
      SLSKD_INCOMPLETE_DIR: /incomplete
      SLSKD_SHARED_DIR: /shares
      SLSKD_SHARE_FILTER: .ini$,Thumbs.db$,.DS_Store$,.lrc$
      SLSKD_HTTP_PORT: 5030
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/docker/slskd/app:/app
      - ${VOL1}/Library/Soulseek/downloads:/downloads
      - ${VOL1}/Library/Soulseek/incomplete:/incomplete
      - ${VOL1}/Library/Media/Music/Imported:/shares/Music:ro
      #- "${VOL1}/Library/Media/Movies:/home/app/shares/Movies:ro"
      #- "${VOL1}/Library/Media/TVShows:/home/app/shares/TVShows:ro"
    
# JACKETT
  jackett:
    image: linuxserver/jackett:${VERSION_JACKETT}
    container_name: jackett
    restart: unless-stopped
    network_mode: service:gluetun
    healthcheck:
      test: "curl ifconfig.me  || exit 1"
      interval: 1m
      timeout: 10s
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/docker/jackett/config:/config

# BYPARR
  byparr:
    image: ghcr.io/thephaseless/byparr:${VERSION_BYPARR}
    container_name: byparr
    restart: unless-stopped
    network_mode: service:gluetun
    healthcheck:
      test: "curl ifconfig.me  || exit 1"
      interval: 1m
      timeout: 10s
    init: true
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /etc/localtime:/etc/localtime:ro

# LIDARR
  lidarr:
    image: linuxserver/lidarr:${VERSION_LIDARR}
    container_name: lidarr
    restart: unless-stopped
    network_mode: service:gluetun
    healthcheck:
      test: "curl ifconfig.me  || exit 1"
      interval: 1m
      timeout: 10s
    environment:
      PUID: 1000
      PGID: 1000
      #DOCKER_MODS: linuxserver/mods:lidarr-flac2mp3
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/docker/lidarr/config:/config
      - ${VOL1}/Library:/data
      - ${VOL1}/.Trash-1000/files/Lidarr:/trash
      - ${VOL1}/Backups/Container/Lidarr:/backups

# RADARR
  radarr:
    image: linuxserver/radarr:${VERSION_RADARR}
    container_name: radarr
    restart: unless-stopped
    network_mode: service:gluetun
    healthcheck:
      test: "curl ifconfig.me  || exit 1"
      interval: 1m
      timeout: 10s
    environment:
      PUID: 1000
      PGID: 1000
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/docker/radarr/config:/config
      - ${VOL1}/Library:/data
      - ${VOL1}/.Trash-1000/files/Radarr:/trash
      - ${VOL1}/Backups/Container/Radarr:/backups

# SONARR
  sonarr:
    image: linuxserver/sonarr:${VERSION_SONARR}
    container_name: sonarr
    restart: unless-stopped
    network_mode: service:gluetun
    healthcheck:
      test: "curl ifconfig.me  || exit 1"
      interval: 1m
      timeout: 10s
    environment:
      PUID: 1000
      PGID: 1000
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/docker/sonarr/config:/config
      - ${VOL1}/Library:/data
      - ${VOL1}/.Trash-1000/files/Sonarr:/trash
      - ${VOL1}/Backups/Container/Sonarr:/backups

  # SOULMATE
  soulmate:
    image: banankungen/soulmate:${VERSION_SOULMATE}
    container_name: soulmate
    restart: unless-stopped
    network_mode: service:gluetun
    healthcheck:
      test: "curl ifconfig.me || exit 1"
      interval: 1m
      timeout: 10s
    environment:
      SLSKD__URL: http://gluetunnet:5030
      SLSKD__KEY: "vx4AIlae8iB1mOz+Ne1oK3e8GX6b8ZEXr7lLnSYnjP0="
      SLSKD__DOWNLOAD_PATH: /downloads/
      SLSKD__PUBLIC_URL: http://192.168.178.13:5133
      LIDARR__URL: http://gluetunnet:8686
      LIDARR__KEY: 119c05ac76f4454aa9eaf09a6f00bf87
      LIDARR__DOWNLOAD_PATH: /data/Soulseek/downloads/
      LIDARR__PUBLIC_URL: http://192.168.178.13:5151
      MAX_CONCURRENT_DOWNLOADS: 4
      INITIAL_WAIT_MINUTES: 0
      REQUIRE_MANUAL_IMPORTS: true
      SEARCH_MISSING: true
      SEARCH_UNMET: false
      STALLED_DOWNLOAD_MINUTES: 60
      IGNORED_LIDARR_ALBUM_TYPES: Album
      AUTOMATIC_LIDARR_IMPORT: true
      DELETE_ERRORED_DOWNLOADS: true
      DELETE_FAILED_IMPORTS: true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/docker/soulmate/config:/config
      - ${VOL1}/Library/Soulseek/downloads:/downloads
     

networks:
  net:
    driver: bridge
