services:

# WIREGUARD
  wireguard:
    image: linuxserver/wireguard:${VERSION_WIREGUARD}
    container_name: wireguard
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE #optional
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    environment:
      PUID: 1001
      PGID: 1001
      SERVERURL: ${ENV_SERVERURL}
      SERVERPORT: 51820
      PEERS: ${ENV_PEERS}
      PEERDNS: ${ENV_PEERDNS}
      INTERNAL_SUBNET: ${ENV_INTERNAL_SUBNET}
      ALLOWEDIPS: ${ENV_ALLOWEDIPS}
      PERSISTENTKEEPALIVE_PEERS:  #optional
      LOG_CONFS: true #optional
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/docker/wireguard/config:/config
      - /lib/modules:/lib/modules #optional
    networks:
      - net
      - public
    ports:
      - ${PORT1_WIREGUARD}:51820/udp 

# DYNDNS
  cloudflare-ddns:
    image: favonia/cloudflare-ddns:latest
    restart: always
    read_only: true
    cap_drop: [all]
    security_opt: [no-new-privileges:true]
    environment:
      CLOUDFLARE_API_TOKEN: ${ENV_DYNDNS_API_TOKEN}
      DOMAINS: ${ENV_DYNDNS_DOMAINS}
      PROXIED: true
      IP6_PROVIDER: none
    networks:
      - net


networks:
  net:
    driver: bridge
  public:
    name: reverseproxy-stack_net
    external: true

