services:

# CADDY
  caddy:
    image: slothcroissant/caddy-cloudflaredns:${VERSION_CADDY}
    container_name: caddy
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/docker/caddy/Caddyfile:/etc/caddy/Caddyfile
      - /home/docker/caddy/site:/srv
      - /home/docker/caddy/data:/data
      - /home/docker/caddy/config:/config
      - /home/docker/caddy/ssl:/ssl
    networks:
      - net
    ports:
      - ${PORT1_CADDY}:80
      - ${PORT2_CADDY}:443
      - ${PORT2_CADDY}:443/udp
    dns:
      - ${DNS1_CADDY}
      - ${DNS2_CADDY}

# DYNDNS
  cloudflare-ddns:
    image: favonia/cloudflare-ddns:latest
    container_name: dyndns
    restart: unless-stopped
    read_only: true
    cap_drop: [all]
    security_opt: [no-new-privileges:true]
    environment:
      CLOUDFLARE_API_TOKEN: ${ENV_DYNDNS_API_TOKEN}
      DOMAINS: ${ENV_DYNDNS_DOMAINS}
      PROXIED: true
      IP6_PROVIDER: none
    networks:
      - net


networks:
  net:
    driver: bridge

